name: animated_flip_counter
description: A widget that animates from one number to another.
version: 0.1.1
homepage: https://github.com/h65wang/flutter-animated-counter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: